### ISSUE TITLE
Your credits

### ISSUE THREAD

**Issue by eried** [jamesshao8/portapack-havoc#2]
Hey @jamesshao8, can you add your credits to the About in this branch https://github.com/jamesshao8/portapack-havoc/tree/shao-credits?

**Comment by jamesshao8** [comment]
Which about do you mean?
I can add the information in the README.md or I can add it to ui_about.hpp so that my credits will be shown in the about page of portapack.

**Comment by eried** [comment]
Yes I mean in the about.hpp, in that scroll text so we send that if the features are accepted :)

**Comment by jamesshao8** [comment]
Hi I have just modified that, and uploaded in my original repo. My credit is above the line of " Thanks and  donators".

**Comment by eried** [comment]
I fixed a bit the style for the about and pushed it too.

BTW your changes are now on the official havoc! except the gps sim for now :D awesome! I want to make my own app and this is super helpful for learning.

I wonder if you will continue fixing your apps?:
1) progress bar on the GPS sim
2) graphics below GPS sim (showing last coord sent, time, etc while playing or some message when not)
3) NTSC support for TV app
4) Device label and such for BLE viewer

I think I could work on 3)

**Comment by jamesshao8** [comment]
Thanks! 
I prefer to do other functions before improving the app that already half done. New apps are always more exciting. Yes you can try to add ntsc, it's not that different. I have achieved ntsc on my.computer program, but I didn't bring it to portapack yet.

I have a portapack developing tutorial:
https://blog.csdn.net/shukebeta008/category_9718353.html

In future, I will add sstv and nova receiver for portapack.

**Comment by eried** [comment]
Great! if you add them in branches you could get them easily into main havoc so everyone can use those new apps. I will check your guide

**Comment by eried** [comment]
> I have a portapack developing tutorial:
> https://blog.csdn.net/shukebeta008/category_9718353.html

I checked your guide, however a lot is translated very strange by google translate :P hahah I think I need to learn it to write an english guide :)

**Comment by jamesshao8** [comment]
I have modifed pocsag transimitter and receiver. I added postive and negative phase selection. With that, portapack can send messages between each others. You can try it if you want. @eried

In future, I am considering making video tutorial on youtube. The content will be about SDR programming, and it will be in English.

**Comment by eried** [comment]
Tuturial would be fantastic. We need more people helping creating cool stuff, there is little documentation and it is quite confusing to start :)

**Comment by eried** [comment]
> The content will be about SDR programming, and it will be in English.

Related question: How do you debug the code? Can you attach a debugger? breakpoints? I am trying to find why https://github.com/furrtek/portapack-havoc/issues/350 happens

**Comment by jamesshao8** [comment]
I dont have a debugger or breakpoints. I test most of program on pc first than bring to portapack. I have a timescope in tv app, and a terminal in nrf app, which could help me during programming.

**Comment by eried** [comment]
I see, I am not sure where I can ask you more things, if is OK here:

why your BTLE uses `audio.hpp`? it is because leftovers of another app? or because a bug if not? I am trying to solve an issue with "Capture" app hanging another app

**Comment by jamesshao8** [comment]
Do you mean the audio.hpp in ui_btle_rx.cpp? It comes with ui_afsk_rx.cpp which btle is modified from. I think it's because originally furrtek wants people to hear the fm demodulated result while decoding it digitally. But this can be removed.
BLE decoding isn't perfect mainly because the bit error, so I didn't remove much extra code especially those for "options" for future development.
You can improve it in anyway you would like.
